# **APRENDIZAGEM NÃO SUPERVISIONADA: ASSOCIAÇÃO**

Este projeto tem por objetivo desenvolver um algoritmo de Machine Learning para associar produtos de mercado.

Os dados foram extraídos do site do Kaggle:

https://www.kaggle.com/heeraldedhia/groceries-dataset

In [6]:
import numpy as np
import pandas as pd

In [7]:
import warnings
warnings.filterwarnings("ignore")

In [8]:
df = pd.read_csv('Groceries_dataset.csv')
df.head()

   Member_number        Date   itemDescription
0           1808  21-07-2015    tropical fruit
1           2552  05-01-2015        whole milk
2           2300  19-09-2015         pip fruit
3           1187  12-12-2015  other vegetables
4           3037  01-02-2015        whole milk

In [9]:
df.shape

(38765, 3)

## **ANÁLISE, TRATAMENTO E PRÉ-PROCESSAMENTO DOS DADOS**

**Valores Missing (NAN)**

In [10]:
df.isnull().sum()

Member_number      0
Date               0
itemDescription    0
dtype: int64

**Análise dos tipos de atributos**

In [12]:
df.dtypes

Member_number       int64
Date               object
itemDescription    object
dtype: object

In [13]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Member_number               int64
Date               datetime64[ns]
itemDescription            object
dtype: object

In [14]:
df["itemDescription"].value_counts().head(30)

itemDescription
whole milk               2502
other vegetables         1898
rolls/buns               1716
soda                     1514
yogurt                   1334
root vegetables          1071
tropical fruit           1032
bottled water             933
sausage                   924
citrus fruit              812
pastry                    785
pip fruit                 744
shopping bags             731
canned beer               717
bottled beer              687
whipped/sour cream        662
newspapers                596
frankfurter               580
brown bread               571
pork                      566
domestic eggs             566
butter                    534
fruit/vegetable juice     518
beef                      516
curd                      514
margarine                 491
coffee                    476
frozen vegetables         425
chicken                   422
white bread               362
Name: count, dtype: int64

In [15]:
df["Member_number"].value_counts().head(10)

Member_number
3180    36
3737    33
3050    33
2051    33
3915    31
2433    31
2271    31
2625    31
3872    30
4875    29
Name: count, dtype: int64

In [16]:
df.head()

   Member_number       Date   itemDescription
0           1808 2015-07-21    tropical fruit
1           2552 2015-01-05        whole milk
2           2300 2015-09-19         pip fruit
3           1187 2015-12-12  other vegetables
4           3037 2015-02-01        whole milk

In [18]:
df2 = df.groupby(['Member_number', 'itemDescription'])['itemDescription'].count().unstack().fillna(0).applymap(lambda x: 1 if x > 0 else 0)

In [19]:
df2

itemDescription,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
Member_number,,,,,,,,,,,,,,,,,,,,,
1000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,0
1001,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,1,0,1,0,0
1002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
4998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4999,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
5000,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
df2.iloc[0:12, 0:12]

itemDescription,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,beverages,bottled beer
Member_number,,,,,,,,,,,,
1000,0,0,0,0,0,0,0,0,0,0,0,0
1001,0,0,0,0,0,0,0,0,1,0,0,0
1002,0,0,0,0,0,0,0,0,0,0,0,0
1003,0,0,0,0,0,0,0,0,0,0,0,0
1004,0,0,0,0,0,0,0,0,0,0,0,0
1005,0,0,0,0,0,0,0,0,0,0,0,0
1006,0,0,0,0,0,0,0,0,0,0,0,1
1008,0,0,0,0,0,0,0,0,0,0,0,0
1009,0,0,0,0,0,0,0,0,0,0,0,0
1010,0,1,0,0,0,0,0,0,0,0,0,0
1011,0,0,0,0,0,0,0,0,0,0,0,0
1012,0,0,0,0,0,0,0,0,0,0,0,0

In [21]:
df2.shape

(3898, 167)

## **APRIORI**

In [22]:
from mlxtend.frequent_patterns import apriori, association_rules

In [23]:
# Gerando a associação
associacao = apriori(df2, min_support=0.05, use_colnames=True)

/home/code-warden/anaconda3/lib/python3.13/site-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [24]:
# Colocando em ordem dos mais frequentes
associacao.sort_values("support", ascending=False).head(10)

      support                        itemsets
55   0.458184                    (whole milk)
37   0.376603              (other vegetables)
41   0.349666                    (rolls/buns)
47   0.313494                          (soda)
56   0.282966                        (yogurt)
51   0.233710                (tropical fruit)
42   0.230631               (root vegetables)
5    0.213699                 (bottled water)
44   0.206003                       (sausage)
116  0.191380  (whole milk, other vegetables)

In [25]:
# Criando as regras de associação
regras = association_rules(associacao, metric="lift")

In [26]:
# Colocando em ordem de suporte, confiança ou grau de associação (Lift)
resultado = regras.sort_values("support", ascending=False)

In [27]:
resultado.head(20)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
118,(whole milk),(other vegetables),0.458184,0.376603,0.191380,0.417693,1.109106,1.0,0.018827,1.070564,0.181562,0.297448,0.065913,0.462934
119,(other vegetables),(whole milk),0.376603,0.458184,0.191380,0.508174,1.109106,1.0,0.018827,1.101643,0.157802,0.297448,0.092265,0.462934
152,(whole milk),(rolls/buns),0.458184,0.349666,0.178553,0.389698,1.114484,1.0,0.018342,1.065592,0.189591,0.283734,0.061555,0.450168
153,(rolls/buns),(whole milk),0.349666,0.458184,0.178553,0.510638,1.114484,1.0,0.018342,1.107190,0.157955,0.283734,0.096813,0.450168
183,(soda),(whole milk),0.313494,0.458184,0.151103,0.481997,1.051973,1.0,0.007465,1.045971,0.071966,0.243489,0.043950,0.405892
182,(whole milk),(soda),0.458184,0.313494,0.151103,0.329787,1.051973,1.0,0.007465,1.024310,0.091184,0.243489,0.023733,0.405892
193,(yogurt),(whole milk),0.282966,0.458184,0.150590,0.532185,1.161510,1.0,0.020940,1.158185,0.193926,0.254996,0.136580,0.430426
192,(whole milk),(yogurt),0.458184,0.282966,0.150590,0.328667,1.161510,1.0,0.020940,1.068076,0.256640,0.254996,0.063737,0.430426
104,(other vegetables),(rolls/buns),0.376603,0.349666,0.146742,0.389646,1.114335,1.0,0.015056,1.065502,0.164589,0.253209,0.061475,0.404654
105,(rolls/buns),(other vegetables),0.349666,0.376603,0.146742,0.419663,1.114335,1.0,0.015056,1.074197,0.157772,0.253209,0.069072,0.404654
112,(soda),(other vegetables),0.313494,0.376603,0.124166,0.396072,1.051695,1.0,0.006103,1.032237,0.071601,0.219402,0.031230,0.362886
113,(other vegetables),(soda),0.376603,0.313494,0.124166,0.329700,1.051695,1.0,0.006103,1.024178,0.078849,0.219402,0.023607,0.362886
120,(yogurt),(other vegetables),0.282966,0.376603,0.120318,0.425204,1.129050,1.0,0.013752,1.084553,0.159406,0.223121,0.077961,0.372343
121,(other vegetables),(yogurt),0.376603,0.282966,0.120318,0.319482,1.129050,1.0,0.013752,1.053660,0.183350,0.223121,0.050927,0.372343
147,(rolls/buns),(soda),0.349666,0.313494,0.119805,0.342627,1.092928,1.0,0.010187,1.044316,0.130743,0.220491,0.042436,0.362393
146,(soda),(rolls/buns),0.313494,0.349666,0.119805,0.382160,1.092928,1.0,0.010187,1.052593,0.123855,0.220491,0.049965,0.362393
187,(tropical fruit),(whole milk),0.233710,0.458184,0.116470,0.498353,1.087672,1.0,0.009388,1.080076,0.105189,0.202407,0.074139,0.376276
186,(whole milk),(tropical fruit),0.458184,0.233710,0.116470,0.254199,1.087672,1.0,0.009388,1.027473,0.148768,0.202407,0.026739,0.376276
162,(whole milk),(root vegetables),0.458184,0.230631,0.113135,0.246920,1.070630,1.0,0.007464,1.021630,0.121758,0.196524,0.021172,0.368733
163,(root vegetables),(whole milk),0.230631,0.458184,0.113135,0.490545,1.070630,1.0,0.007464,1.063522,0.085746,0.196524,0.059728,0.368733