# **APRENDIZAGEM NÃO SUPERVISIONADA: ASSOCIAÇÃO**

# **ECLAT**

In [1]:
!pip install pyECLAT

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pyECLAT) (2.2.3)
Requirement already satisfied: numpy>=1.17.4 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pyECLAT) (2.1.3)
Requirement already satisfied: tqdm>=4.41.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pyECLAT) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.3->pyECLAT) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: six>=1.5 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2

In [2]:
from pyECLAT import Example1

In [5]:
dados = Example1().get()

In [6]:
dados

        0      1       2       3
0    milk   beer   bread  butter
1   coffe  bread  butter     NaN
2   coffe  bread  butter     NaN
3    milk  coffe   bread  butter
4    beer    NaN     NaN     NaN
5  butter    NaN     NaN     NaN
6   bread    NaN     NaN     NaN
7    bean    NaN     NaN     NaN
8    rice   bean     NaN     NaN
9    rice    NaN     NaN     NaN

In [9]:
from pyECLAT import ECLAT
eclat = ECLAT(data=dados, verbose=True)

100%|██████████| 7/7 [00:00<00:00, 1821.01it/s]
100%|██████████| 7/7 [00:00<00:00, 126552.28it/s]
100%|██████████| 7/7 [00:00<00:00, 3375.50it/s]

In [10]:
eclat.df_bin

   coffe  bread  beer  milk  rice  butter  bean
0      0      1     1     1     0       1     0
1      1      1     0     0     0       1     0
2      1      1     0     0     0       1     0
3      1      1     0     1     0       1     0
4      0      0     1     0     0       0     0
5      0      0     0     0     0       1     0
6      0      1     0     0     0       0     0
7      0      0     0     0     0       0     1
8      0      0     0     0     1       0     1
9      0      0     0     0     1       0     0

In [11]:
eclat.uniq_

['coffe', 'bread', 'beer', 'milk', nan, 'rice', 'butter', 'bean']

In [12]:
indices, suporte = eclat.fit(min_support=0.1, min_combination=2, max_combination=4)

Combination 2 by 2

21it [00:00, 211.93it/s]

Combination 3 by 3

35it [00:00, 186.11it/s]

Combination 4 by 4

35it [00:00, 355.42it/s]

In [13]:
indices

{'coffe & bread': [1, 2, 3],
 'coffe & milk': [3],
 'coffe & butter': [1, 2, 3],
 'bread & beer': [0],
 'bread & milk': [0, 3],
 'bread & butter': [0, 1, 2, 3],
 'beer & milk': [0],
 'beer & butter': [0],
 'milk & butter': [0, 3],
 'rice & bean': [8],
 'coffe & bread & milk': [3],
 'coffe & bread & butter': [1, 2, 3],
 'coffe & milk & butter': [3],
 'bread & beer & milk': [0],
 'bread & beer & butter': [0],
 'bread & milk & butter': [0, 3],
 'beer & milk & butter': [0],
 'coffe & bread & milk & butter': [3],
 'bread & beer & milk & butter': [0]}

In [14]:
suporte

{'coffe & bread': 0.3,
 'coffe & milk': 0.1,
 'coffe & butter': 0.3,
 'bread & beer': 0.1,
 'bread & milk': 0.2,
 'bread & butter': 0.4,
 'beer & milk': 0.1,
 'beer & butter': 0.1,
 'milk & butter': 0.2,
 'rice & bean': 0.1,
 'coffe & bread & milk': 0.1,
 'coffe & bread & butter': 0.3,
 'coffe & milk & butter': 0.1,
 'bread & beer & milk': 0.1,
 'bread & beer & butter': 0.1,
 'bread & milk & butter': 0.2,
 'beer & milk & butter': 0.1,
 'coffe & bread & milk & butter': 0.1,
 'bread & beer & milk & butter': 0.1}

# **APRIORI**

In [15]:
from pyECLAT import Example1
dados = Example1().get()
dados

        0      1       2       3
0    milk   beer   bread  butter
1   coffe  bread  butter     NaN
2   coffe  bread  butter     NaN
3    milk  coffe   bread  butter
4    beer    NaN     NaN     NaN
5  butter    NaN     NaN     NaN
6   bread    NaN     NaN     NaN
7    bean    NaN     NaN     NaN
8    rice   bean     NaN     NaN
9    rice    NaN     NaN     NaN

In [16]:
dados.shape

(10, 4)

In [19]:
from pyECLAT import ECLAT
eclat = ECLAT(data=dados, verbose=True)
dados2 = eclat.df_bin
dados2

100%|██████████| 7/7 [00:00<00:00, 1864.02it/s]
100%|██████████| 7/7 [00:00<00:00, 71089.90it/s]
100%|██████████| 7/7 [00:00<00:00, 4684.13it/s]

   coffe  bread  beer  milk  rice  butter  bean
0      0      1     1     1     0       1     0
1      1      1     0     0     0       1     0
2      1      1     0     0     0       1     0
3      1      1     0     1     0       1     0
4      0      0     1     0     0       0     0
5      0      0     0     0     0       1     0
6      0      1     0     0     0       0     0
7      0      0     0     0     0       0     1
8      0      0     0     0     1       0     1
9      0      0     0     0     1       0     0

In [22]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.15.3)
Requirement already satisfied: numpy>=1.16.2 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.1.3)
Requirement already satisfied: pandas>=0.24.2 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.6.1)
Requirement already satisfied: matplotlib>=3.0.0 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 7.6 MB/s eta 0:00:00a 0:00:01
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4

In [23]:
from mlxtend.frequent_patterns import apriori, association_rules

In [ ]:
# Gerando associacao
associacao = apriori(dados2, min_support=0.05, use_colnames=True)

/home/code-warden/anaconda3/lib/python3.13/site-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [25]:
associacao

    support                      itemsets
0       0.3                       (coffe)
1       0.5                       (bread)
2       0.2                        (beer)
3       0.2                        (milk)
4       0.2                        (rice)
5       0.5                      (butter)
6       0.2                        (bean)
7       0.3                (coffe, bread)
8       0.1                 (coffe, milk)
9       0.3               (butter, coffe)
10      0.1                 (beer, bread)
11      0.2                 (milk, bread)
12      0.4               (butter, bread)
13      0.1                  (beer, milk)
14      0.1                (beer, butter)
15      0.2                (butter, milk)
16      0.1                  (rice, bean)
17      0.1          (coffe, milk, bread)
18      0.3        (butter, coffe, bread)
19      0.1         (butter, coffe, milk)
20      0.1           (beer, milk, bread)
21      0.1         (beer, bread, butter)
22      0.2         (butter, milk, bread)
23      0.1          (beer, milk, butter)
24      0.1  (butter, coffe, milk, bread)
25      0.1   (beer, milk, bread, butter)

In [27]:
# Colocando a associação em ordem dos mais frequentes
associacao.sort_values(by='support', ascending=False).head(15)

    support                itemsets
1       0.5                 (bread)
5       0.5                (butter)
12      0.4         (butter, bread)
0       0.3                 (coffe)
9       0.3         (butter, coffe)
7       0.3          (coffe, bread)
18      0.3  (butter, coffe, bread)
3       0.2                  (milk)
4       0.2                  (rice)
2       0.2                  (beer)
22      0.2   (butter, milk, bread)
6       0.2                  (bean)
15      0.2          (butter, milk)
11      0.2           (milk, bread)
8       0.1           (coffe, milk)

In [45]:
# Criando as regras de associação
regras = association_rules(associacao, metric='confidence')

In [46]:
resultado = regras.sort_values(by='lift', ascending=False)

In [47]:
resultado.head(30)

              antecedents      consequents  ...  certainty  kulczynski
25  (beer, bread, butter)           (milk)  ...        1.0       0.750
27          (beer, bread)   (butter, milk)  ...        1.0       0.750
28         (beer, butter)    (milk, bread)  ...        1.0       0.750
19         (beer, butter)           (milk)  ...        1.0       0.750
14          (beer, bread)           (milk)  ...        1.0       0.750
9                  (milk)  (butter, bread)  ...        1.0       0.750
26           (beer, milk)  (butter, bread)  ...        1.0       0.625
22          (coffe, milk)  (butter, bread)  ...        1.0       0.625
6                 (coffe)  (butter, bread)  ...        1.0       0.875
8           (milk, bread)         (butter)  ...        1.0       0.700
3                 (coffe)          (bread)  ...        1.0       0.800
4         (butter, coffe)          (bread)  ...        1.0       0.800
2                 (coffe)         (butter)  ...        1.0       0.800
20  (butter, coffe, milk)          (bread)  ...        1.0       0.600
18           (beer, milk)         (butter)  ...        1.0       0.600
12          (coffe, milk)          (bread)  ...        1.0       0.600
11                 (milk)          (bread)  ...        1.0       0.700
5          (coffe, bread)         (butter)  ...        1.0       0.800
7          (butter, milk)          (bread)  ...        1.0       0.700
10                 (milk)         (butter)  ...        1.0       0.700
15          (coffe, milk)         (butter)  ...        1.0       0.600
13           (beer, milk)          (bread)  ...        1.0       0.600
24   (beer, milk, butter)          (bread)  ...        1.0       0.600
17         (beer, butter)          (bread)  ...        1.0       0.600
16          (beer, bread)         (butter)  ...        1.0       0.600
21   (coffe, milk, bread)         (butter)  ...        1.0       0.600
23    (beer, milk, bread)         (butter)  ...        1.0       0.600
0                (butter)          (bread)  ...        0.6       0.800
1                 (bread)         (butter)  ...        0.6       0.800

[29 rows x 14 columns]