# **APRENDIZAGEM NÃO SUPERVISIONADA: ASSOCIAÇÃO**

# **ECLAT**

In [1]:
!pip install pyECLAT

Collecting pyECLAT
  Downloading pyECLAT-1.0.2-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: pandas>=0.25.3 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pyECLAT) (2.2.3)
Requirement already satisfied: numpy>=1.17.4 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pyECLAT) (2.1.3)
Requirement already satisfied: tqdm>=4.41.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pyECLAT) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.3->pyECLAT) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.3->pyECLAT) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from pandas>=0.25.3->pyECLAT) (2025.2)
Requirement already satisfied: six>=1.5 in /home/code-warden/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->pyECLAT) (1.17.0)
Downloading pyECLAT-1.0.2-py3-none-any.whl (6.3 kB)
Installing collected packages: pyECLAT
Successfully installed pyECLAT-1.0.2

In [2]:
from pyECLAT import Example1

In [5]:
dados = Example1().get()

In [6]:
dados

        0      1       2       3
0    milk   beer   bread  butter
1   coffe  bread  butter     NaN
2   coffe  bread  butter     NaN
3    milk  coffe   bread  butter
4    beer    NaN     NaN     NaN
5  butter    NaN     NaN     NaN
6   bread    NaN     NaN     NaN
7    bean    NaN     NaN     NaN
8    rice   bean     NaN     NaN
9    rice    NaN     NaN     NaN

In [9]:
from pyECLAT import ECLAT
eclat = ECLAT(data=dados, verbose=True)

100%|██████████| 7/7 [00:00<00:00, 1821.01it/s]
100%|██████████| 7/7 [00:00<00:00, 126552.28it/s]
100%|██████████| 7/7 [00:00<00:00, 3375.50it/s]

In [10]:
eclat.df_bin

   coffe  bread  beer  milk  rice  butter  bean
0      0      1     1     1     0       1     0
1      1      1     0     0     0       1     0
2      1      1     0     0     0       1     0
3      1      1     0     1     0       1     0
4      0      0     1     0     0       0     0
5      0      0     0     0     0       1     0
6      0      1     0     0     0       0     0
7      0      0     0     0     0       0     1
8      0      0     0     0     1       0     1
9      0      0     0     0     1       0     0

In [11]:
eclat.uniq_

['coffe', 'bread', 'beer', 'milk', nan, 'rice', 'butter', 'bean']

In [12]:
indices, suporte = eclat.fit(min_support=0.1, min_combination=2, max_combination=4)

Combination 2 by 2

21it [00:00, 211.93it/s]

Combination 3 by 3

35it [00:00, 186.11it/s]

Combination 4 by 4

35it [00:00, 355.42it/s]

In [13]:
indices

{'coffe & bread': [1, 2, 3],
 'coffe & milk': [3],
 'coffe & butter': [1, 2, 3],
 'bread & beer': [0],
 'bread & milk': [0, 3],
 'bread & butter': [0, 1, 2, 3],
 'beer & milk': [0],
 'beer & butter': [0],
 'milk & butter': [0, 3],
 'rice & bean': [8],
 'coffe & bread & milk': [3],
 'coffe & bread & butter': [1, 2, 3],
 'coffe & milk & butter': [3],
 'bread & beer & milk': [0],
 'bread & beer & butter': [0],
 'bread & milk & butter': [0, 3],
 'beer & milk & butter': [0],
 'coffe & bread & milk & butter': [3],
 'bread & beer & milk & butter': [0]}

In [14]:
suporte

{'coffe & bread': 0.3,
 'coffe & milk': 0.1,
 'coffe & butter': 0.3,
 'bread & beer': 0.1,
 'bread & milk': 0.2,
 'bread & butter': 0.4,
 'beer & milk': 0.1,
 'beer & butter': 0.1,
 'milk & butter': 0.2,
 'rice & bean': 0.1,
 'coffe & bread & milk': 0.1,
 'coffe & bread & butter': 0.3,
 'coffe & milk & butter': 0.1,
 'bread & beer & milk': 0.1,
 'bread & beer & butter': 0.1,
 'bread & milk & butter': 0.2,
 'beer & milk & butter': 0.1,
 'coffe & bread & milk & butter': 0.1,
 'bread & beer & milk & butter': 0.1}