# **APRENDIZAGEM SUPERVISIONADA: REGRESSÃO**

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('housing.csv')
df.head()

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [4]:
df.shape

(489, 4)

## **EXPLORAÇÃO E TRATAMENTO DE DADOS**

Valores Missing (NAN)

In [5]:
# Relação da quantidade
df.isnull().sum()

RM         0
LSTAT      0
PTRATIO    0
MEDV       0
dtype: int64

**Análise dos atributos**

In [6]:
df.dtypes

RM         float64
LSTAT      float64
PTRATIO    float64
MEDV       float64
dtype: object

**Dados Estatísticos**

In [7]:
df.describe()

               RM       LSTAT     PTRATIO          MEDV
count  489.000000  489.000000  489.000000  4.890000e+02
mean     6.240288   12.939632   18.516564  4.543429e+05
std      0.643650    7.081990    2.111268  1.653403e+05
min      3.561000    1.980000   12.600000  1.050000e+05
25%      5.880000    7.370000   17.400000  3.507000e+05
50%      6.185000   11.690000   19.100000  4.389000e+05
75%      6.575000   17.120000   20.200000  5.187000e+05
max      8.398000   37.970000   22.000000  1.024800e+06

**Análise de Outliers**

In [8]:
import plotly.express as px

In [9]:
boxplot = px.box(df, y="RM")
boxplot.show()

In [10]:
boxplot = px.box(df, y="LSTAT")
boxplot.show()

In [11]:
boxplot = px.box(df, y="PTRATIO")
boxplot.show()

In [12]:
boxplot = px.box(df, y="MEDV")
boxplot.show()